name: "522-project"

channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipykernel
  - pandas
  - scikit-learn
  - altair
  - vl-convert-python
  - pyarrow
  - pip
  - pip:
      - ucimlrepo
      - vegafusion
