name: base
channels:
  - conda-forge
dependencies:
  - python=3.12
  - conda
  - mamba=2.1.1
  - pip
  - miniforge_console_shortcut=1
  - otter-grader
  - pandas
  - jupyterlab-spellchecker
  - jupyterlab=4
  - jupyterlab-git
  - jupytext
  - altair
  - palmerpenguins
  - pandoc
  - nb_conda_kernels
prefix: C:\Users\binep\miniforge3
