# Install the course conda environment with the following command:
# conda env create -f env-dsci-571.yml
# Once you install it, you should be able to see it in your Jupyter Lab.
# If not, check the documentation here: https://ipython.readthedocs.io/en/stable/install/kernel_install.html
name: "522-project"

channels:
  - conda-forge
  - pytorch
  - anaconda
  - plotly
  - defaults
dependencies:
  - python==3.13.5
  - ipykernel
  - matplotlib
  - pandas
  - nb_conda_kernels
  - scikit-learn
  - requests
  - ipython
  - graphviz
  - python-graphviz
  - jinja2
  - lightgbm
  - torchvision
  - torchaudio
  - pytorch
  - autograd
  - plotly
  - panel
  - watchfiles
  - altair-all
  - vega_datasets # Example data
  - pip
  - pip:
      - mglearn
      - otter-grader
      - graphviz
      - nbformat
      - nbclient
      - transformers
      - datasets
      - psutil
